### ISSUE TITLE
最新版启动会弹个报错窗口

### ISSUE THREAD

**Issue by foxdodo** [rosuH/EasyWatermark#151]
手机三星s20＋ oneui3.1
                    Dear developer, here are my crash info:
                    
                                            Crash in main:
                    java.lang.ExceptionInInitializerError
	at me.rosuh.easywatermark.MyApp.onConfigurationChanged(Unknown Source:5)
	at android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:6119)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:6408)
	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:6294)
	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:42)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0501c0
	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:285)
	at android.content.res.Resources.getColor(Resources.java:1164)
	at android.content.Context.getColor(Context.java:681)
	at b0.a$d.a(Unknown Source:0)
	at b0.a.b(Unknown Source:6)
	at x5.a.<clinit>(Unknown Source:29)
	... 14 more
    
                    =====================
                    APP:
                    20702, 2.7.2, release 
                    Devices:
                    11, 30, y2q, SM-G9860, y2qzcx, samsung
                    =====================
                    当反馈的问题有效，并被修复或加入新版本时，您的名字或邮件出现在更新日志弹窗中。我们会对您的信息作遮挡处理，不会出现全称。
 如果您不愿意出现，请标注：我不愿意。即可
                    =====================
                    2022-03-15

**Comment by rosuH** [comment]
感谢反馈，请尝试新版本https://github.com/rosuH/EasyWatermark/releases/tag/2.7.3
