### ISSUE TITLE
[BUG] Crashed when toggling dark mode.

### ISSUE THREAD

**Issue by ryuunoakaihitomi** [rosuH/EasyWatermark#96]
```
2021-10-19 00:24:57.346 3570-3570/me.rosuh.easywatermark.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: me.rosuh.easywatermark.debug, PID: 3570
    java.lang.IllegalArgumentException: width and height must be > 0
...
        at android.graphics.Bitmap.createScaledBitmap(Bitmap.java:807)
        at androidx.core.graphics.drawable.DrawableKt.toBitmap(Drawable.kt:54)
        at androidx.core.graphics.drawable.DrawableKt.toBitmap$default(Drawable.kt:45)
        at me.rosuh.easywatermark.widget.ColoredImageVIew.onDraw(ColoredImageVIew.kt:71)
        at android.view.View.draw(View.java:21547)
...
```

```
lavender:/ $ getprop ro.build.fingerprint
xiaomi/lavender/lavender:10/QKQ1.190910.002/V12.5.3.0.QFGCNXM:user/release-keys

```

**Comment by rosuH** [comment]
Thank you! Will be fixed in the next version. 😃
